---
name: Backstage Exporter

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  backstage-exporter:
    name: Backstage Exporter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aurora-is-near/github-helpers@main
        id: backstage-exporter
        with:
          helper: backstage-export
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backstage_url: ${{ secrets.BACKSTAGE_URL }}
          template_path: templates
          output_path: .

      - name: Commit exports
        run: |
          git config user.name 'Backstage Exporter'
          git config user.email 'security@aurora.dev'
          git diff --quiet || (git add . && git commit -m "chore(backstage): 🥷🏽 automatic re-export")
          git push
